variables = {
    "air_temp": {
        "vargem": "TMPF",
        "VNUM": "1",
        "long_name": "The latest 1-minute mean air temperature",
        "incoming_unit": "degC",
        "final_unit": "degC",
    },
    "mean_humidity": {
        "vargem": "RELH",
        "VNUM": "1",
        "long_name": "The latest 1-minute mean relative humidity",
        "incoming_unit": "pct",
        "final_unit": "pct",
    },    
    "wind_speed": {
        "vargem": "SKNT",
        "VNUM": "1",
        "long_name": "The latest 10-minute mean wind direction and wind speed and maximum gust",
        "incoming_unit": "km/h",
        "final_unit": "m/s",
        "var_dim": {"value": "10", 
                    "unit": "minute", 
                    "statistic": "mean"},
    },
    "wind_gust":{
        "vargem": "GUST",
        "VNUM": "1",
        "long_name": "The latest 10-minute maximum wind gust",
        "incoming_unit": "km/h",
        "final_unit": "m/s",
        "var_dim": {"value": "10", 
                    "unit": "minute", 
                    "statistic": "max"},
    },
    "mean_pressure": {
        "vargem": "PMSL",
        "VNUM": "1",
        "long_name": "The latest 1-minute mean sea level pressure",
        "incoming_unit": "hPa",
        "final_unit": "Pa",
    },
    "solar_radiation": {
        "vargem": "SOLR",
        "VNUM": "1",
        "long_name": "Global Solar Radiation (Daily)",
        "incoming_unit": "W/m²",
        "final_unit": "W/m²",
        "var_dim": {"value": "24", 
                    "unit": "hour", 
                    "statistic": "mean"},
    },
    "diffuse_radiation": {
        "vargem": "DIFR",
        "VNUM": "1",
        "long_name": "Diffuse Radiation (Daily)",
        "incoming_unit": "W/m²",
        "final_unit": "W/m²",
        "var_dim": {"value": "24", 
                    "unit": "hour", 
                    "statistic": "mean"},
    },  
    "grass_min_temp": {
        "vargem": "GSMN",
        "VNUM": "1",
        "long_name": "the latest 1-minute mean grass temperature from 5:00 p.m. to 8:00 a.m. the following date Hong Kong time",
        "incoming_unit": "degC",
        "final_unit": "degC",
    },
    "visibility": {
        "vargem": "VSBY",
        "VNUM": "1",
        "long_name": "the latest 10-minute mean visibility",
        "incoming_unit": "km",
        "final_unit": "statutemile",
        "var_dim": {"value": "10", 
                    "unit": "minute", 
                    "statistic": "mean"},
    },
}
